language: node_js
node_js:
  - "5.1"
  - "5.0"
  - "4.1"
  - "4.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g gulp
  - gulp install
script: gulp unit
